###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

version: '2'
services:
#REDIS
  api-redis:
    image: phpdockerio/redis:latest
    container_name: api-redis


#PHP
  api-application:
    build:
      context: .
      dockerfile: application/Dockerfile
      args:
          - PROJECT_PATH=/go/src/tournamentAPI
          - PUID=1000
    container_name: api-application
    ports:
      - "8081:8081"
    volumes:
      - ..:/go/src/tournamentAPI
    depends_on:
      - api-redis

